require("rofviv.plugins-setup")
require("rofviv.core.options")
require("rofviv.core.keymaps")
require("rofviv.core.colorscheme")
require("rofviv.plugins.comment")
require("rofviv.plugins.nvim-tree")
require("rofviv.plugins.lualine")
require("rofviv.plugins.telescope")
require("rofviv.plugins.nvim-cmp")
require("rofviv.plugins.lsp.mason")
require("rofviv.plugins.lsp.lpssaga")
require("rofviv.plugins.lsp.lpsconfig")
require("rofviv.plugins.lsp.null-ls")
require("rofviv.plugins.autopairs")
require("rofviv.plugins.treesitter")
require("rofviv.plugins.gitsigns")
require("rofviv.plugins.flutter-tools")
require("rofviv.plugins.dap")
-- require("rofviv.plugins.dap-ui")
-- require("rofviv.plugins.vim-rainbow")
